version: '3'

services:
  redis:
    image: redis:alpine
    networks:
      - db-network
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - db-network
  web:
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "8888:8888"
    depends_on:
      - db
      - redis
    networks:
      - db-network

networks:
  db-network: