# Generated by Django 3.2.16 on 2022-10-27 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(default='Scheduled', max_length=50)),
                ('errors', models.TextField(default=None, null=True)),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hosts.host')),
            ],
        ),
    ]
