# Generated by Django 3.2.16 on 2022-10-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='tags',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
    ]
