# Generated by Django 3.2.16 on 2022-10-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_scan_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='phase',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Running', 'Running'), ('Complete', 'Complete'), ('Error', 'Error')], default='Scheduled', max_length=50),
        ),
    ]
