# Generated by Django 3.2.16 on 2022-10-28 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_alter_host_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='domain',
            field=models.CharField(max_length=255, validators=[django.core.validators.URLValidator]),
        ),
    ]
