# Generated by Django 3.2.16 on 2022-10-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_alter_host_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='criticality',
            field=models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=50),
        ),
    ]
